### ISSUE TITLE
綁架相樞

### ISSUE THREAD

**Issue by locke12456** [GlossMod/UnityScriptTrainer#13]
手賤跑去綁架相樞，然後就噴了
log: 
2022-10-15 13:40:58.6008|ERROR|Main|GameData.Program|System.Exception: 9518 is either XiangshuInfected or XiangshuMinion, thus cannot be converted from random enemy to intelligent character
   at GameData.Domains.Character.CharacterDomain.ConvertRandomEnemy(DataContext context, Character character, Location location) in C:\GitLab-Runner\builds\n1JyyH3P\0\scroll-of-taiwu\game-data\GameData\Domains\Character\Creation\CharacterDomain_Calc_Creation.cs:line 569
   at GameData.Domains.Character.CharacterDomain.AddKidnappedCharacter(DataContext context, Character character, Character kidnappedChar, ItemKey ropeItemKey) in C:\GitLab-Runner\builds\n1JyyH3P\0\scroll-of-taiwu\game-data\GameData\Domains\Character\CharacterDomain_Calc_Kidnap.cs:line 214
   at GameData.Domains.Character.CharacterDomain.GmCmd_MakeCharacterKidnapped(DataContext context, Int32 characterId, Int32 targetCharacterId) in C:\GitLab-Runner\builds\n1JyyH3P\0\scroll-of-taiwu\game-data\GameData\Domains\Character\CharacterDomain_Calc_GmCommand.cs:line 464
   at DMD<GameData.Domains.Character.CharacterDomain::CallMethod>(CharacterDomain this, Operation operation, RawDataPool argDataPool, RawDataPool returnDataPool, DataContext context)
   at DMD<GameData.GameDataBridge.GameDataBridge::ProcessMethodCall>(Operation operation, RawDataPool argDataPool, DataContext context)
   at GameData.GameDataBridge.GameDataBridge.ProcessOperations(DataContext context)
   at GameData.GameDataBridge.GameDataBridge.RunMainLoop()
   at GameData.Program.Main(String[] args)

**Comment by 3DMXM** [comment]
那你就别绑架它
